############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "About"
url = "/about"
weight = 2

[[main]]
name = "Database"
url = "/database"
weight = 3

[[main]]
weight = 4
name = "Divisions"

[[main]]
parent = "Divisions"
name = "Manhattan, KS"
url = "/manhattan-ks"

[[main]]
parent = "Divisions"
name = "Topeka, KS"
url = "/topeka-ks"

# footer menu
[[footer]]
name = "About"
url = "/about"
weight = 1

[[footer]]
name = "Elements"
url = "/elements"
weight = 2

[[footer]]
name = "Privacy Policy"
url = "/privacy-policy"
weight = 3
